version: '3.8'

services:
  database:
    image: postgres:15.3
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 100
      start_period: 5s

  server:
    build:
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:5000"
    depends_on:
      database: { condition: service_healthy }

volumes:
  pg_data:
