"""Add original id

Revision ID: 2f334d8ec0cb
Revises: c94de0e5c2db
Create Date: 2023-07-22 12:54:54.644866

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f334d8ec0cb"
down_revision = "c94de0e5c2db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flats", schema=None) as batch_op:
        batch_op.add_column(sa.Column("original_id", sa.BigInteger(), nullable=False))
        batch_op.create_unique_constraint(None, ["original_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("flats", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("original_id")

    # ### end Alembic commands ###
